### ISSUE TITLE
Code evaluation for Lists

### ISSUE THREAD

**Issue by Aetet** [dart-lang/devtools-frontend#63]
we have following dart code

```dart
final a = [1,2,3];
```

if we paste `a` in console - it evaluates as array, but display as List.

So it hasn't methods like where, removeWhere etc.

It would be extremely helpful if List have dart List API instead of JS.

**Comment by alan-knight** [comment]
DDC compiles the Dart List default constructors into JavaScript arrays. But it also augments JavaScript arrays with Dart methods. So in the console you should be able to write those methods. e.g. I can write

      finalList.where((int x) => x >= 2).toList() 
        ==> List<int> length 2

The only tricky thing is that the inference requires me to type the parameter to the closure or else it gets a type failure because `where` won't accept a closure that takes dynamic.

What are you finding yourself unable to do?

**Comment by alan-knight** [comment]
And I note that the having to type the input parameter is due to a temporary workaround I've had to put in for top level variables. It shouldn't apply to locals or instance attributes.
